### ISSUE TITLE
Gradle version conflicts over com.android.support:appcompat

### ISSUE THREAD

**Issue by jimbo1qaz** [AllanWang/KAU#164]
After adding `ca.allanwang.kau:core:3.7.0`, Android Studio displays an red squiggly  line under my `implementation 'com.android.support:appcompat-v7:27.1.1'`:

>All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 27.0.2.

My build.gradle: https://gist.github.com/jimbo1qaz/b0677466dbde9c8bc37e854a089469e0#file-build-gradle

**Comment by AllanWang** [comment]
With KAU, you actually don't need any of the appcompat (and constraintlayout) dependencies, as they are included. Removing those lines will allow you to use the current versions within KAU.

If you just started using this project, you can also use version d540934915da26ab2cec4c897e973be35e0bfe24, which has the latest appcompat versions. I'm in the middle of some major changes, which is why it is not yet released. To use this, replace `:3.7.0` with `:d540934915da26ab2cec4c897e973be35e0bfe24`

You can look at all the versions for the latest dev commit [here](https://github.com/AllanWang/KAU/blob/dev/buildSrc/src/main/groovy/ca/allanwang/kau/Versions.groovy)
